 var a=20,b=10;
var c=a+b;
console.log(c);
var d=a-b;
console.log(d);
var e=(a++)+(++b);
console.log(e);
var f=a&b;
console.log(f);
var g=a&&b;
console.log(g);
var h=(a>=b);
console.log(h);
var i=a>>2;
console.log(i);